//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: IOIFUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_IOIF_IOIFUI_BASE_CLASSES_H
#define _MODULES_IOIF_IOIFUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/button.h>
#include <wx/frame.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/textctrl.h>
#include <wx/tglbtn.h>
#include <wx/slider.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class IoifConfigurationDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer3;
    wxFlexGridSizer* flexGridSizer5;
    wxStaticText* m_staticText9;
    wxChoice* m_port;
    wxStdDialogButtonSizer* m_stdBtnSizer7;
    wxButton* m_button13;
    wxButton* m_button15;

protected:

public:
    wxStaticText* GetStaticText9() { return m_staticText9; }
    wxChoice* GetPort() { return m_port; }
    IoifConfigurationDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("IOIF Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~IoifConfigurationDialogBase();
};


class IoifDisplayBase : public wxFrame
{
protected:
    wxBoxSizer* boxSizer19;
    wxNotebook* m_notebook21;
    wxPanel* m_panel23;
    wxFlexGridSizer* flexGridSizer29;
    wxStaticText* m_staticText31;
    wxTextCtrl* m_in0;
    wxStaticText* m_staticText35;
    wxTextCtrl* m_in1;
    wxStaticText* m_staticText39;
    wxTextCtrl* m_in2;
    wxStaticText* m_staticText43;
    wxTextCtrl* m_in3;
    wxStaticText* m_staticText47;
    wxTextCtrl* m_in4;
    wxStaticText* m_staticText51;
    wxTextCtrl* m_in5;
    wxStaticText* m_staticText55;
    wxTextCtrl* m_in6;
    wxStaticText* m_staticText59;
    wxTextCtrl* m_in7;
    wxPanel* m_panel25;
    wxGridSizer* gridSizer78;
    wxToggleButton* m_out0;
    wxToggleButton* m_out1;
    wxToggleButton* m_out2;
    wxToggleButton* m_out3;
    wxToggleButton* m_out4;
    wxStaticText* m_staticText84;
    wxButton* m_allOff;
    wxButton* m_allOn;
    wxPanel* m_panel27;
    wxFlexGridSizer* flexGridSizer86;
    wxStaticText* m_staticText88;
    wxTextCtrl* m_dacOutput;
    wxStaticText* m_staticText92;
    wxSlider* m_dacSelect;

protected:
    virtual void onOUT0(wxCommandEvent& event) { event.Skip(); }
    virtual void onOut1(wxCommandEvent& event) { event.Skip(); }
    virtual void onOut2(wxCommandEvent& event) { event.Skip(); }
    virtual void onOut3(wxCommandEvent& event) { event.Skip(); }
    virtual void onOut4(wxCommandEvent& event) { event.Skip(); }
    virtual void onAllOff(wxCommandEvent& event) { event.Skip(); }
    virtual void onAllOn(wxCommandEvent& event) { event.Skip(); }
    virtual void onDacChanged(wxScrollEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText31() { return m_staticText31; }
    wxTextCtrl* GetIn0() { return m_in0; }
    wxStaticText* GetStaticText35() { return m_staticText35; }
    wxTextCtrl* GetIn1() { return m_in1; }
    wxStaticText* GetStaticText39() { return m_staticText39; }
    wxTextCtrl* GetIn2() { return m_in2; }
    wxStaticText* GetStaticText43() { return m_staticText43; }
    wxTextCtrl* GetIn3() { return m_in3; }
    wxStaticText* GetStaticText47() { return m_staticText47; }
    wxTextCtrl* GetIn4() { return m_in4; }
    wxStaticText* GetStaticText51() { return m_staticText51; }
    wxTextCtrl* GetIn5() { return m_in5; }
    wxStaticText* GetStaticText55() { return m_staticText55; }
    wxTextCtrl* GetIn6() { return m_in6; }
    wxStaticText* GetStaticText59() { return m_staticText59; }
    wxTextCtrl* GetIn7() { return m_in7; }
    wxPanel* GetPanel23() { return m_panel23; }
    wxToggleButton* GetOut0() { return m_out0; }
    wxToggleButton* GetOut1() { return m_out1; }
    wxToggleButton* GetOut2() { return m_out2; }
    wxToggleButton* GetOut3() { return m_out3; }
    wxToggleButton* GetOut4() { return m_out4; }
    wxStaticText* GetStaticText84() { return m_staticText84; }
    wxButton* GetAllOff() { return m_allOff; }
    wxButton* GetAllOn() { return m_allOn; }
    wxPanel* GetPanel25() { return m_panel25; }
    wxStaticText* GetStaticText88() { return m_staticText88; }
    wxTextCtrl* GetDacOutput() { return m_dacOutput; }
    wxStaticText* GetStaticText92() { return m_staticText92; }
    wxSlider* GetDacSelect() { return m_dacSelect; }
    wxPanel* GetPanel27() { return m_panel27; }
    wxNotebook* GetNotebook21() { return m_notebook21; }
    IoifDisplayBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT(""), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~IoifDisplayBase();
};

#endif
