//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: InputViewUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _COMMON_GUI_INPUTVIEWUI_BASE_CLASSES_H
#define _COMMON_GUI_INPUTVIEWUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/richtext/richtextctrl.h>
#include <wx/timer.h>
#include "Common/graphwindow.h"
#include <wx/listbox.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class InputViewerBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer55;
    wxNotebook* m_tabs;
    wxPanel* m_panelCurrent;
    wxBoxSizer* boxSizer63;
    wxRichTextCtrl* m_currentStatus;
    wxTimer* m_timer83;

protected:
    virtual void DriveProcess(wxTimerEvent& event) { event.Skip(); }

public:
    wxRichTextCtrl* GetCurrentStatus() { return m_currentStatus; }
    wxPanel* GetPanelCurrent() { return m_panelCurrent; }
    wxNotebook* GetTabs() { return m_tabs; }
    wxTimer* GetTimer83() { return m_timer83; }
    InputViewerBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Input Viewer"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~InputViewerBase();
};


class InputViewerHistoryBase : public wxPanel
{
protected:
    wxBoxSizer* boxSizer75;
    MRL::GraphWindow* m_graph;
    wxListBox* m_history;

protected:

public:
    MRL::GraphWindow* GetGraph() { return m_graph; }
    wxListBox* GetHistory() { return m_history; }
    InputViewerHistoryBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~InputViewerHistoryBase();
};

#endif
