//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: MariaDbPubSetup.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "MariaDbPubSetup.h"


// Declare the bitmap loading function
extern void wxCraftery5DLmNInitBitmapResources();

static bool bBitmapLoaded = false;


MariaDbSetupDialogBase::MariaDbSetupDialogBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCraftery5DLmNInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    boxSizer3 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer3);
    
    gridSizer5 = new wxGridSizer(0, 2, 0, 0);
    
    boxSizer3->Add(gridSizer5, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText47 = new wxStaticText(this, wxID_ANY, _("Host"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_staticText47, 0, wxALL, WXC_FROM_DIP(5));
    
    m_host = new wxTextCtrl(this, wxID_ANY, wxT("localhost"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 3000
    m_host->SetHint(wxT(""));
    #endif
    
    gridSizer5->Add(m_host, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText13 = new wxStaticText(this, wxID_ANY, _("Database"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_staticText13, 0, wxALL, WXC_FROM_DIP(5));
    
    m_database = new wxTextCtrl(this, wxID_ANY, wxT("OPCSERVANT"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 3000
    m_database->SetHint(wxT(""));
    #endif
    
    gridSizer5->Add(m_database, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText17 = new wxStaticText(this, wxID_ANY, _("Port"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_staticText17, 0, wxALL, WXC_FROM_DIP(5));
    
    m_port = new wxSpinCtrl(this, wxID_ANY, wxT("0"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxSP_ARROW_KEYS);
    m_port->SetRange(0, 10000);
    m_port->SetValue(0);
    
    gridSizer5->Add(m_port, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText21 = new wxStaticText(this, wxID_ANY, _("Username"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_staticText21, 0, wxALL, WXC_FROM_DIP(5));
    
    m_username = new wxTextCtrl(this, wxID_ANY, wxT("user"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 3000
    m_username->SetHint(wxT(""));
    #endif
    
    gridSizer5->Add(m_username, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText25 = new wxStaticText(this, wxID_ANY, _("Password"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_staticText25, 0, wxALL, WXC_FROM_DIP(5));
    
    m_password = new wxTextCtrl(this, wxID_ANY, wxT("password"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 3000
    m_password->SetHint(wxT(""));
    #endif
    
    gridSizer5->Add(m_password, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_enable = new wxCheckBox(this, wxID_ANY, _("Enabled"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_enable->SetValue(false);
    
    gridSizer5->Add(m_enable, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button37 = new wxButton(this, wxID_ANY, _("Test ..."), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer5->Add(m_button37, 0, wxALL, WXC_FROM_DIP(5));
    
    gridSizer5->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    m_stdBtnSizer7 = new wxStdDialogButtonSizer();
    
    boxSizer3->Add(m_stdBtnSizer7, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button9 = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer7->AddButton(m_button9);
    
    m_button11 = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer7->AddButton(m_button11);
    m_stdBtnSizer7->Realize();
    
    SetName(wxT("MariaDbSetupDialogBase"));
    SetSize(500,300);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_button37->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MariaDbSetupDialogBase::OnTest), NULL, this);
    m_button9->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MariaDbSetupDialogBase::OnOK), NULL, this);
    
}

MariaDbSetupDialogBase::~MariaDbSetupDialogBase()
{
    m_button37->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MariaDbSetupDialogBase::OnTest), NULL, this);
    m_button9->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MariaDbSetupDialogBase::OnOK), NULL, this);
    
}
