//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: ValuesUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_VALUES_VALUESUI_BASE_CLASSES_H
#define _MODULES_VALUES_VALUESUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/spinctrl.h>
#include "wx/spinctrl.h"
#include <wx/checkbox.h>
#include <wx/button.h>
#include <wx/combobox.h>
#include <wx/panel.h>
#include <wx/gbsizer.h>
#include <wx/listbox.h>
#include <wx/grid.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class ValueConfigurationDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer181;
    wxFlexGridSizer* flexGridSizer183;
    wxStaticText* m_staticText185;
    wxChoice* m_object;
    wxStaticText* m_staticText189;
    wxSpinCtrlDouble* m_scale;
    wxStaticText* m_staticText193;
    wxSpinCtrlDouble* m_offset;
    wxFlexGridSizer* flexGridSizer197;
    wxStaticText* m_staticText199;
    wxSpinCtrlDouble* m_hihi;
    wxCheckBox* m_hihiEnabled;
    wxStaticText* m_staticText205;
    wxSpinCtrlDouble* m_hilo;
    wxCheckBox* m_hiloEnabled;
    wxStaticText* m_staticText211;
    wxSpinCtrlDouble* m_lohi;
    wxCheckBox* m_lohiEnabled;
    wxStaticText* m_staticText217;
    wxSpinCtrlDouble* m_lolo;
    wxCheckBox* m_loloEnabled;
    wxStdDialogButtonSizer* m_stdBtnSizer225;
    wxButton* m_button227;
    wxButton* m_button229;

protected:
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText185() { return m_staticText185; }
    wxChoice* GetObject() { return m_object; }
    wxStaticText* GetStaticText189() { return m_staticText189; }
    wxSpinCtrlDouble* GetScale() { return m_scale; }
    wxStaticText* GetStaticText193() { return m_staticText193; }
    wxSpinCtrlDouble* GetOffset() { return m_offset; }
    wxStaticText* GetStaticText199() { return m_staticText199; }
    wxSpinCtrlDouble* GetHihi() { return m_hihi; }
    wxCheckBox* GetHihiEnabled() { return m_hihiEnabled; }
    wxStaticText* GetStaticText205() { return m_staticText205; }
    wxSpinCtrlDouble* GetHilo() { return m_hilo; }
    wxCheckBox* GetHiloEnabled() { return m_hiloEnabled; }
    wxStaticText* GetStaticText211() { return m_staticText211; }
    wxSpinCtrlDouble* GetLohi() { return m_lohi; }
    wxCheckBox* GetLohiEnabled() { return m_lohiEnabled; }
    wxStaticText* GetStaticText217() { return m_staticText217; }
    wxSpinCtrlDouble* GetLolo() { return m_lolo; }
    wxCheckBox* GetLoloEnabled() { return m_loloEnabled; }
    ValueConfigurationDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Value Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,500), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~ValueConfigurationDialogBase();
};


class ValueSelectAliasDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer68;
    wxFlexGridSizer* flexGridSizer70;
    wxStaticText* m_staticText72;
    wxComboBox* m_aliasList;
    wxStdDialogButtonSizer* m_stdBtnSizer76;
    wxButton* m_button78;
    wxButton* m_button80;

protected:
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText72() { return m_staticText72; }
    wxComboBox* GetAliasList() { return m_aliasList; }
    ValueSelectAliasDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Select Alias"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~ValueSelectAliasDialogBase();
};


class ValueGroupConfigurationDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer84;
    wxPanel* m_panel86;
    wxGridBagSizer* gridBagSizer94;
    wxListBox* m_listValues;
    wxButton* m_button98;
    wxButton* m_button100;
    wxButton* m_button102;
    wxButton* m_button116;
    wxFlexGridSizer* flexGridSizer122;
    wxStaticText* m_staticText124;
    wxSpinCtrl* m_measureInterval;
    wxStaticText* m_staticText128;
    wxSpinCtrl* m_publishInterval;
    wxCheckBox* m_enabled;
    wxCheckBox* m_enableTabView;
    wxStdDialogButtonSizer* m_stdBtnSizer88;
    wxButton* m_button90;
    wxButton* m_button92;

protected:
    virtual void onAdd(wxCommandEvent& event) { event.Skip(); }
    virtual void onEdit(wxCommandEvent& event) { event.Skip(); }
    virtual void onRemove(wxCommandEvent& event) { event.Skip(); }
    virtual void onAlias(wxCommandEvent& event) { event.Skip(); }
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxListBox* GetListValues() { return m_listValues; }
    wxButton* GetButton98() { return m_button98; }
    wxButton* GetButton100() { return m_button100; }
    wxButton* GetButton102() { return m_button102; }
    wxButton* GetButton116() { return m_button116; }
    wxStaticText* GetStaticText124() { return m_staticText124; }
    wxSpinCtrl* GetMeasureInterval() { return m_measureInterval; }
    wxStaticText* GetStaticText128() { return m_staticText128; }
    wxSpinCtrl* GetPublishInterval() { return m_publishInterval; }
    wxCheckBox* GetEnabled() { return m_enabled; }
    wxCheckBox* GetEnableTabView() { return m_enableTabView; }
    wxPanel* GetPanel86() { return m_panel86; }
    ValueGroupConfigurationDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Value Group Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~ValueGroupConfigurationDialogBase();
};


class ValueGroupPanelBase : public wxPanel
{
protected:
    wxBoxSizer* boxSizer136;
    wxGrid* m_Values;
    wxStaticText* m_status;
    wxTimer* m_periodicTimer;

protected:
    virtual void onSizeGrid(wxSizeEvent& event) { event.Skip(); }
    virtual void onPeriodicTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxGrid* GetValues() { return m_Values; }
    wxStaticText* GetStatus() { return m_status; }
    wxTimer* GetPeriodicTimer() { return m_periodicTimer; }
    ValueGroupPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxTAB_TRAVERSAL);
    virtual ~ValueGroupPanelBase();
};

#endif
