//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: NodeFlowUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "NodeFlowUI.h"


// Declare the bitmap loading function
extern void wxCrafterCOw9lwInitBitmapResources();

static bool bBitmapLoaded = false;


NodeFlowConfigurationBase::NodeFlowConfigurationBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafterCOw9lwInitBitmapResources();
        bBitmapLoaded = true;
    }
    
    boxSizer3 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer3);
    
    flexGridSizer23 = new wxFlexGridSizer(0, 3, 0, 0);
    flexGridSizer23->SetFlexibleDirection( wxBOTH );
    flexGridSizer23->SetNonFlexibleGrowMode( wxFLEX_GROWMODE_SPECIFIED );
    flexGridSizer23->AddGrowableCol(1);
    
    boxSizer3->Add(flexGridSizer23, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_Flow = new wxStaticText(this, wxID_ANY, _("Flow"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    flexGridSizer23->Add(m_Flow, 0, wxALL, WXC_FROM_DIP(5));
    
    wxArrayString m_flowListArr;
    m_flowList = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), m_flowListArr, 0);
    
    flexGridSizer23->Add(m_flowList, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_editFlow = new wxButton(this, wxID_ANY, _("Edit ..."), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    flexGridSizer23->Add(m_editFlow, 0, wxALL, WXC_FROM_DIP(5));
    
    m_enabled = new wxCheckBox(this, wxID_ANY, _("Enabled"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    m_enabled->SetValue(false);
    
    flexGridSizer23->Add(m_enabled, 0, wxALL, WXC_FROM_DIP(5));
    
    gridSizer35 = new wxGridSizer(0, 3, 0, 0);
    
    boxSizer3->Add(gridSizer35, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_button37 = new wxButton(this, wxID_ANY, _("Add"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer35->Add(m_button37, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button39 = new wxButton(this, wxID_ANY, _("Remove"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer35->Add(m_button39, 0, wxALL, WXC_FROM_DIP(5));
    
    m_inputName = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 3000
    m_inputName->SetHint(wxT(""));
    #endif
    
    gridSizer35->Add(m_inputName, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    wxArrayString m_listInputsArr;
    m_listInputs = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), m_listInputsArr, wxLB_SINGLE);
    
    boxSizer3->Add(m_listInputs, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_stdBtnSizer11 = new wxStdDialogButtonSizer();
    
    boxSizer3->Add(m_stdBtnSizer11, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button13 = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer11->AddButton(m_button13);
    
    m_button15 = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer11->AddButton(m_button15);
    m_stdBtnSizer11->Realize();
    
    SetName(wxT("NodeFlowConfigurationBase"));
    SetMinClientSize(wxSize(500,400));
    SetSize(wxDLG_UNIT(this, wxSize(500,400)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_button37->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onAdd), NULL, this);
    m_button39->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onRemove), NULL, this);
    m_button15->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onOK), NULL, this);
    
}

NodeFlowConfigurationBase::~NodeFlowConfigurationBase()
{
    m_button37->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onAdd), NULL, this);
    m_button39->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onRemove), NULL, this);
    m_button15->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(NodeFlowConfigurationBase::onOK), NULL, this);
    
}
