//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: VisualCalcUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_VISUALCALC_VISUALCALCUI_BASE_CLASSES_H
#define _MODULES_VISUALCALC_VISUALCALCUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/timer.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/button.h>
#include <wx/imaglist.h>
#include <wx/stattext.h>
#include <wx/spinctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class VisualCalcTabWindowBase : public wxPanel
{
protected:
    wxBoxSizer* boxSizer83;
    wxNotebook* m_notebook;
    wxTimer* m_timer133;

protected:
    virtual void onStartTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxNotebook* GetNotebook() { return m_notebook; }
    wxTimer* GetTimer133() { return m_timer133; }
    VisualCalcTabWindowBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxTAB_TRAVERSAL);
    virtual ~VisualCalcTabWindowBase();
};


class VisualCalcConfigurationDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer51;
    wxGridSizer* gridSizer115;
    wxButton* m_button117;
    wxButton* m_button119;
    wxButton* m_button121;
    wxButton* m_button123;
    wxButton* m_button125;
    wxButton* m_button127;
    wxButton* m_button129;
    wxNotebook* m_notebook;
    wxPanel* m_panelSetup;
    wxBoxSizer* boxSizer103;
    wxFlexGridSizer* flexGridSizer105;
    wxStaticText* m_staticText107;
    wxSpinCtrl* m_spinCtrl109;
    wxStaticText* m_staticText111;
    wxSpinCtrl* m_spinCtrl113;
    wxStdDialogButtonSizer* m_stdBtnSizer53;
    wxButton* m_button55;
    wxButton* m_button57;
    wxTimer* m_timer67;

protected:
    virtual void onNew(wxCommandEvent& event) { event.Skip(); }
    virtual void onOpen(wxCommandEvent& event) { event.Skip(); }
    virtual void onSave(wxCommandEvent& event) { event.Skip(); }
    virtual void onSaveAs(wxCommandEvent& event) { event.Skip(); }
    virtual void onAutomatic(wxCommandEvent& event) { event.Skip(); }
    virtual void onManual(wxCommandEvent& event) { event.Skip(); }
    virtual void onUpdate(wxCommandEvent& event) { event.Skip(); }
    virtual void onStartTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxButton* GetButton117() { return m_button117; }
    wxButton* GetButton119() { return m_button119; }
    wxButton* GetButton121() { return m_button121; }
    wxButton* GetButton123() { return m_button123; }
    wxButton* GetButton125() { return m_button125; }
    wxButton* GetButton127() { return m_button127; }
    wxButton* GetButton129() { return m_button129; }
    wxStaticText* GetStaticText107() { return m_staticText107; }
    wxSpinCtrl* GetSpinCtrl109() { return m_spinCtrl109; }
    wxStaticText* GetStaticText111() { return m_staticText111; }
    wxSpinCtrl* GetSpinCtrl113() { return m_spinCtrl113; }
    wxPanel* GetPanelSetup() { return m_panelSetup; }
    wxNotebook* GetNotebook() { return m_notebook; }
    wxTimer* GetTimer67() { return m_timer67; }
    VisualCalcConfigurationDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Visual Calc Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX);
    virtual ~VisualCalcConfigurationDialogBase();
};

#endif
