//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: VisualCalcUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "VisualCalcUI.h"


// Declare the bitmap loading function
extern void wxCrafter4yUaw3InitBitmapResources();

static bool bBitmapLoaded = false;


VisualCalcTabWindowBase::VisualCalcTabWindowBase(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
    : wxPanel(parent, id, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafter4yUaw3InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    boxSizer83 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer83);
    
    m_notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxBK_DEFAULT);
    m_notebook->SetName(wxT("m_notebook"));
    
    boxSizer83->Add(m_notebook, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_timer133 = new wxTimer;
    m_timer133->Start(10, true);
    
    SetName(wxT("VisualCalcTabWindowBase"));
    SetSize(wxDLG_UNIT(this, wxSize(800,600)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    // Connect events
    m_timer133->Connect(wxEVT_TIMER, wxTimerEventHandler(VisualCalcTabWindowBase::onStartTimer), NULL, this);
    
}

VisualCalcTabWindowBase::~VisualCalcTabWindowBase()
{
    m_timer133->Disconnect(wxEVT_TIMER, wxTimerEventHandler(VisualCalcTabWindowBase::onStartTimer), NULL, this);
    
    m_timer133->Stop();
    wxDELETE( m_timer133 );

}

VisualCalcConfigurationDialogBase::VisualCalcConfigurationDialogBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxCrafter4yUaw3InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    boxSizer51 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer51);
    
    gridSizer115 = new wxGridSizer(0, 8, 0, 0);
    
    boxSizer51->Add(gridSizer115, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_button117 = new wxButton(this, wxID_ANY, _("New"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button117, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button119 = new wxButton(this, wxID_ANY, _("Open ..."), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button119, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button121 = new wxButton(this, wxID_ANY, _("Save"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button121, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button123 = new wxButton(this, wxID_ANY, _("Save As ..."), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button123, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button125 = new wxButton(this, wxID_ANY, _("Automatic"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button125, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button127 = new wxButton(this, wxID_ANY, _("Manual"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button127, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button129 = new wxButton(this, wxID_ANY, _("Update"), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), 0);
    
    gridSizer115->Add(m_button129, 0, wxALL, WXC_FROM_DIP(5));
    
    m_notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxBK_DEFAULT);
    m_notebook->SetName(wxT("m_notebook"));
    
    boxSizer51->Add(m_notebook, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_panelSetup = new wxPanel(m_notebook, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_notebook, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    m_notebook->AddPage(m_panelSetup, _("Setup"), false);
    
    boxSizer103 = new wxBoxSizer(wxVERTICAL);
    m_panelSetup->SetSizer(boxSizer103);
    
    flexGridSizer105 = new wxFlexGridSizer(0, 2, 0, 0);
    flexGridSizer105->SetFlexibleDirection( wxBOTH );
    flexGridSizer105->SetNonFlexibleGrowMode( wxFLEX_GROWMODE_SPECIFIED );
    
    boxSizer103->Add(flexGridSizer105, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_staticText107 = new wxStaticText(m_panelSetup, wxID_ANY, _("Static Text Label"), wxDefaultPosition, wxDLG_UNIT(m_panelSetup, wxSize(-1,-1)), 0);
    
    flexGridSizer105->Add(m_staticText107, 0, wxALL, WXC_FROM_DIP(5));
    
    m_spinCtrl109 = new wxSpinCtrl(m_panelSetup, wxID_ANY, wxT("0"), wxDefaultPosition, wxDLG_UNIT(m_panelSetup, wxSize(-1,-1)), wxSP_ARROW_KEYS);
    m_spinCtrl109->SetRange(0, 100);
    m_spinCtrl109->SetValue(0);
    
    flexGridSizer105->Add(m_spinCtrl109, 0, wxALL, WXC_FROM_DIP(5));
    
    m_staticText111 = new wxStaticText(m_panelSetup, wxID_ANY, _("Static Text Label"), wxDefaultPosition, wxDLG_UNIT(m_panelSetup, wxSize(-1,-1)), 0);
    
    flexGridSizer105->Add(m_staticText111, 0, wxALL, WXC_FROM_DIP(5));
    
    m_spinCtrl113 = new wxSpinCtrl(m_panelSetup, wxID_ANY, wxT("0"), wxDefaultPosition, wxDLG_UNIT(m_panelSetup, wxSize(-1,-1)), wxSP_ARROW_KEYS);
    m_spinCtrl113->SetRange(0, 100);
    m_spinCtrl113->SetValue(0);
    
    flexGridSizer105->Add(m_spinCtrl113, 0, wxALL, WXC_FROM_DIP(5));
    
    m_stdBtnSizer53 = new wxStdDialogButtonSizer();
    
    boxSizer51->Add(m_stdBtnSizer53, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button55 = new wxButton(this, wxID_CANCEL, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer53->AddButton(m_button55);
    
    m_button57 = new wxButton(this, wxID_OK, wxT(""), wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), 0);
    m_stdBtnSizer53->AddButton(m_button57);
    m_stdBtnSizer53->Realize();
    
    m_timer67 = new wxTimer;
    m_timer67->Start(10, true);
    
    
    #if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(m_notebook)){
        wxPersistenceManager::Get().RegisterAndRestore(m_notebook);
    } else {
        wxPersistenceManager::Get().Restore(m_notebook);
    }
    #endif
    
    SetName(wxT("VisualCalcConfigurationDialogBase"));
    SetMinClientSize(wxSize(800,600));
    SetSize(wxDLG_UNIT(this, wxSize(800,600)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    m_button117->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onNew), NULL, this);
    m_button119->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onOpen), NULL, this);
    m_button121->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onSave), NULL, this);
    m_button123->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onSaveAs), NULL, this);
    m_button125->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onAutomatic), NULL, this);
    m_button127->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onManual), NULL, this);
    m_button129->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onUpdate), NULL, this);
    m_timer67->Connect(wxEVT_TIMER, wxTimerEventHandler(VisualCalcConfigurationDialogBase::onStartTimer), NULL, this);
    
}

VisualCalcConfigurationDialogBase::~VisualCalcConfigurationDialogBase()
{
    m_button117->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onNew), NULL, this);
    m_button119->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onOpen), NULL, this);
    m_button121->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onSave), NULL, this);
    m_button123->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onSaveAs), NULL, this);
    m_button125->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onAutomatic), NULL, this);
    m_button127->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onManual), NULL, this);
    m_button129->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(VisualCalcConfigurationDialogBase::onUpdate), NULL, this);
    m_timer67->Disconnect(wxEVT_TIMER, wxTimerEventHandler(VisualCalcConfigurationDialogBase::onStartTimer), NULL, this);
    
    m_timer67->Stop();
    wxDELETE( m_timer67 );

}
