//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: LwsApexUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_LWSAPEX_LWSAPEXUI_BASE_CLASSES_H
#define _MODULES_LWSAPEX_LWSAPEXUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/spinctrl.h>
#include <wx/checkbox.h>
#include <wx/button.h>
#include <wx/panel.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class LwsApexConfigurationDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer3;
    wxFlexGridSizer* flexGridSizer5;
    wxStaticText* m_staticText39;
    wxTextCtrl* m_address;
    wxStaticText* m_staticText7;
    wxSpinCtrl* m_purgeTime;
    wxStaticText* m_staticText11;
    wxSpinCtrl* m_sampleTime;
    wxCheckBox* m_Enabled;
    wxStdDialogButtonSizer* m_stdBtnSizer15;
    wxButton* m_button17;
    wxButton* m_button19;

protected:
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText39() { return m_staticText39; }
    wxTextCtrl* GetAddress() { return m_address; }
    wxStaticText* GetStaticText7() { return m_staticText7; }
    wxSpinCtrl* GetPurgeTime() { return m_purgeTime; }
    wxStaticText* GetStaticText11() { return m_staticText11; }
    wxSpinCtrl* GetSampleTime() { return m_sampleTime; }
    wxCheckBox* GetEnabled() { return m_Enabled; }
    LwsApexConfigurationDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("LWS Apex Particle Counter"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~LwsApexConfigurationDialogBase();
};


class LwsApexPanelBase : public wxPanel
{
protected:
    wxGridSizer* gridSizer25;
    wxStaticText* m_staticText27;
    wxStaticText* m_value_0_5;
    wxStaticText* m_staticText31;
    wxStaticText* m_value_5_0;
    wxStaticText* m_staticText35;
    wxStaticText* m_status;

protected:

public:
    wxStaticText* GetStaticText27() { return m_staticText27; }
    wxStaticText* GetValue_0_5() { return m_value_0_5; }
    wxStaticText* GetStaticText31() { return m_staticText31; }
    wxStaticText* GetValue_5_0() { return m_value_5_0; }
    wxStaticText* GetStaticText35() { return m_staticText35; }
    wxStaticText* GetStatus() { return m_status; }
    LwsApexPanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~LwsApexPanelBase();
};

#endif
