//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: HarnessUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _OPCSERVANT_HARNESS_HARNESSUI_BASE_CLASSES_H
#define _OPCSERVANT_HARNESS_HARNESSUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class HarnessTestDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer3;
    wxPanel* m_panel5;
    wxBoxSizer* boxSizer15;
    wxChoice* m_port;
    wxTextCtrl* m_sendText;
    wxTextCtrl* m_responseText;
    wxTextCtrl* m_notifyText;
    wxGridSizer* gridSizer29;
    wxButton* m_button23;
    wxButton* m_button31;
    wxStdDialogButtonSizer* m_stdBtnSizer9;
    wxButton* m_button11;
    wxButton* m_button13;
    wxTimer* m_timer25;

protected:
    virtual void onSend(wxCommandEvent& event) { event.Skip(); }
    virtual void onConnect(wxCommandEvent& event) { event.Skip(); }
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }
    virtual void onCancel(wxCommandEvent& event) { event.Skip(); }
    virtual void onTick(wxTimerEvent& event) { event.Skip(); }

public:
    wxChoice* GetPort() { return m_port; }
    wxTextCtrl* GetSendText() { return m_sendText; }
    wxTextCtrl* GetResponseText() { return m_responseText; }
    wxTextCtrl* GetNotifyText() { return m_notifyText; }
    wxButton* GetButton23() { return m_button23; }
    wxButton* GetButton31() { return m_button31; }
    wxPanel* GetPanel5() { return m_panel5; }
    wxTimer* GetTimer25() { return m_timer25; }
    HarnessTestDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Harness"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~HarnessTestDialogBase();
};

#endif
