//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: HttpSendUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_HTTPSEND_HTTPSENDUI_BASE_CLASSES_H
#define _MODULES_HTTPSEND_HTTPSENDUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/spinctrl.h>
#include <wx/checkbox.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class HttpSendSetupDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer3;
    wxFlexGridSizer* flexGridSizer5;
    wxStaticText* m_staticText51;
    wxTextCtrl* m_host;
    wxStaticText* m_staticText55;
    wxSpinCtrl* m_port;
    wxStaticText* m_staticText43;
    wxTextCtrl* m_url;
    wxStaticText* m_staticText47;
    wxTextCtrl* m_filter;
    wxCheckBox* m_enable;
    wxStdDialogButtonSizer* m_stdBtnSizer7;
    wxButton* m_button9;
    wxButton* m_button11;

protected:
    virtual void OnOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText51() { return m_staticText51; }
    wxTextCtrl* GetHost() { return m_host; }
    wxStaticText* GetStaticText55() { return m_staticText55; }
    wxSpinCtrl* GetPort() { return m_port; }
    wxStaticText* GetStaticText43() { return m_staticText43; }
    wxTextCtrl* GetUrl() { return m_url; }
    wxStaticText* GetStaticText47() { return m_staticText47; }
    wxTextCtrl* GetFilter() { return m_filter; }
    wxCheckBox* GetEnable() { return m_enable; }
    HttpSendSetupDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Http Send Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(300,400), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~HttpSendSetupDialogBase();
};

#endif
