//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: OsClientUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _OPCSERVANT_OSCLIENT_OSCLIENTUI_BASE_CLASSES_H
#define _OPCSERVANT_OSCLIENT_OSCLIENTUI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/listbook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/grid.h>
#include <wx/listbox.h>
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/timectrl.h>
#include <wx/dateevt.h>
#include <wx/datectrl.h>
#include <wx/dataview.h>
#include "m_datasourcemodel.h"
#include <wx/menu.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class OpcClientMainFrameBase : public wxFrame
{
protected:
    wxBoxSizer* boxSizer3;
    wxListbook* m_listbook11;
    wxPanel* m_panelStatus;
    wxBoxSizer* boxSizer29;
    wxGrid* m_statusGrid;
    wxPanel* m_panelPlan;
    wxBoxSizer* boxSizer33;
    wxPanel* m_panel124;
    wxPanel* m_panelReports;
    wxBoxSizer* boxSizer39;
    wxPanel* m_panel41;
    wxBoxSizer* boxSizer43;
    wxBoxSizer* boxSizer82;
    wxListBox* m_listReports;
    wxGridSizer* gridSizer84;
    wxButton* m_buttonNewReport;
    wxButton* m_buttonRemoveReport;
    wxPanel* m_panel47;
    wxBoxSizer* boxSizer52;
    wxFlexGridSizer* flexGridSizer54;
    wxStaticText* m_staticText66;
    wxTimePickerCtrl* m_timeFrom;
    wxDatePickerCtrl* m_dateFrom;
    wxStaticText* m_staticText72;
    wxTimePickerCtrl* m_timeTo;
    wxDatePickerCtrl* m_dateTo;
    wxBoxSizer* boxSizer112;
    wxDataViewListCtrl* m_selectedDataSource;
    wxBoxSizer* boxSizer118;
    wxButton* m_buttonAddReportDataSource;
    wxButton* m_buttonRemoveReportDataSource;
    wxGridSizer* gridSizer56;
    wxButton* m_buttonViewReport;
    wxButton* m_buttonMakeReport;
    wxPanel* m_panelMessages;
    wxBoxSizer* boxSizer35;
    wxListBox* m_listMessages;
    wxGridSizer* gridSizer126;
    wxButton* m_buttonClearMessages;
    wxPanel* m_panelDataSources;
    wxBoxSizer* boxSizer92;
    wxDataViewCtrl* m_dataSources;
    wxObjectDataPtr<m_dataSourceModel> m_dataSourcesModel;

    wxGridSizer* gridSizer96;
    wxButton* m_buttonSubscriptions;
    wxMenuBar* m_menuBar21;
    wxMenu* m_menuFile;
    wxMenuItem* m_menuItemOpen;
    wxMenuItem* m_menuItemSave;
    wxMenuItem* m_menuItemSaveAs;
    wxMenuItem* m_menuItemRestore;
    wxMenuItem* m_menuItemSetup;
    wxMenuItem* m_menuItemExit;

protected:
    virtual void onReportSelect(wxCommandEvent& event) { event.Skip(); }
    virtual void onNewReport(wxCommandEvent& event) { event.Skip(); }
    virtual void onRemoveReport(wxCommandEvent& event) { event.Skip(); }
    virtual void onAddReportDataSource(wxCommandEvent& event) { event.Skip(); }
    virtual void onRemoveReportDataSource(wxCommandEvent& event) { event.Skip(); }
    virtual void onViewReport(wxCommandEvent& event) { event.Skip(); }
    virtual void onMakeReport(wxCommandEvent& event) { event.Skip(); }
    virtual void onClearMessages(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOpen(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSave(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSaveAs(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRestore(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSetup(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }

public:
    wxGrid* GetStatusGrid() { return m_statusGrid; }
    wxPanel* GetPanelStatus() { return m_panelStatus; }
    wxPanel* GetPanel124() { return m_panel124; }
    wxPanel* GetPanelPlan() { return m_panelPlan; }
    wxListBox* GetListReports() { return m_listReports; }
    wxButton* GetButtonNewReport() { return m_buttonNewReport; }
    wxButton* GetButtonRemoveReport() { return m_buttonRemoveReport; }
    wxStaticText* GetStaticText66() { return m_staticText66; }
    wxTimePickerCtrl* GetTimeFrom() { return m_timeFrom; }
    wxDatePickerCtrl* GetDateFrom() { return m_dateFrom; }
    wxStaticText* GetStaticText72() { return m_staticText72; }
    wxTimePickerCtrl* GetTimeTo() { return m_timeTo; }
    wxDatePickerCtrl* GetDateTo() { return m_dateTo; }
    wxDataViewListCtrl* GetSelectedDataSource() { return m_selectedDataSource; }
    wxButton* GetButtonAddReportDataSource() { return m_buttonAddReportDataSource; }
    wxButton* GetButtonRemoveReportDataSource() { return m_buttonRemoveReportDataSource; }
    wxButton* GetButtonViewReport() { return m_buttonViewReport; }
    wxButton* GetButtonMakeReport() { return m_buttonMakeReport; }
    wxPanel* GetPanel47() { return m_panel47; }
    wxPanel* GetPanel41() { return m_panel41; }
    wxPanel* GetPanelReports() { return m_panelReports; }
    wxListBox* GetListMessages() { return m_listMessages; }
    wxButton* GetButtonClearMessages() { return m_buttonClearMessages; }
    wxPanel* GetPanelMessages() { return m_panelMessages; }
    wxDataViewCtrl* GetDataSources() { return m_dataSources; }
    wxButton* GetButtonSubscriptions() { return m_buttonSubscriptions; }
    wxPanel* GetPanelDataSources() { return m_panelDataSources; }
    wxListbook* GetListbook11() { return m_listbook11; }
    wxMenuBar* GetMenuBar21() { return m_menuBar21; }
    OpcClientMainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Opc Client"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(1024,800), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~OpcClientMainFrameBase();
};

#endif
