#ifndef DATASOURCE_GLOBAL_H
#define DATASOURCE_GLOBAL_H


#if defined(DATASOURCE_LIBRARY)
#  define DATASOURCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATASOURCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATASOURCE_GLOBAL_H
