//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: PropertyPanels.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _NODEFLOW_NODEFLOW_PROPERTYPANELS_BASE_CLASSES_H
#define _NODEFLOW_NODEFLOW_PROPERTYPANELS_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/toolbar.h>
#include <wx/propgrid/manager.h>
#include <wx/button.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class PropertiesEditorDialogBase : public wxDialog
{
public:
    enum {
        ID_SETTINGS = 10001,
        ID_NOTES = 10002,
    };
protected:
    wxBoxSizer* boxSizer;
    wxToolBar* m_toolbar;
    wxPropertyGridManager* m_properties;
    wxStdDialogButtonSizer* m_stdBtnSizer25;
    wxButton* m_okButton;
    wxButton* m_button29;

protected:
    virtual void OnNotes(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSettings(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxToolBar* GetToolbar() { return m_toolbar; }
    wxPropertyGridManager* GetProperties() { return m_properties; }
    PropertiesEditorDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Properties Editor"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,500), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX);
    virtual ~PropertiesEditorDialogBase();
};


class PropertiesViewerPaneBase : public wxPanel
{
protected:
    wxBoxSizer* boxSizer;
    wxToolBar* m_toolbar115;
    wxStaticText* m_type;
    wxPropertyGridManager* m_properties;

protected:
    virtual void OnNotes(wxCommandEvent& event) { event.Skip(); }

public:
    wxToolBar* GetToolbar115() { return m_toolbar115; }
    wxStaticText* GetType() { return m_type; }
    wxPropertyGridManager* GetProperties() { return m_properties; }
    PropertiesViewerPaneBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~PropertiesViewerPaneBase();
};


class PropertiesViewerDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer;
    wxToolBar* m_toolbar;
    wxPropertyGridManager* m_properties;
    wxStdDialogButtonSizer* m_stdBtnSizer49;
    wxButton* m_button51;

protected:
    virtual void OnNotes(wxCommandEvent& event) { event.Skip(); }
    virtual void OnClose(wxCommandEvent& event) { event.Skip(); }

public:
    wxToolBar* GetToolbar() { return m_toolbar; }
    wxPropertyGridManager* GetProperties() { return m_properties; }
    PropertiesViewerDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Properties Viewer"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,400), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxMAXIMIZE_BOX);
    virtual ~PropertiesViewerDialogBase();
};

#endif
