//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: SPS30UI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MODULES_SPS30_SPS30UI_BASE_CLASSES_H
#define _MODULES_SPS30_SPS30UI_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/button.h>
#include <wx/spinctrl.h>
#include <wx/checkbox.h>
#include <wx/grid.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class SPS30SetupDialogBase : public wxDialog
{
protected:
    wxBoxSizer* boxSizer15;
    wxPanel* m_panel622;
    wxFlexGridSizer* flexGridSizer751;
    wxStaticText* m_staticText753;
    wxButton* m_buttonConfigure;
    wxPanel* m_panel265;
    wxFlexGridSizer* flexGridSizer280;
    wxStaticText* m_staticText282;
    wxSpinCtrl* m_MeasureInterval;
    wxStaticText* m_staticText286;
    wxSpinCtrl* m_PublishInterval;
    wxCheckBox* m_Enabled;
    wxCheckBox* m_EnableTabView;
    wxStdDialogButtonSizer* m_stdBtnSizer33;
    wxButton* m_button35;
    wxButton* m_button37;

protected:
    virtual void onConfigure(wxCommandEvent& event) { event.Skip(); }
    virtual void onOk(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText753() { return m_staticText753; }
    wxButton* GetButtonConfigure() { return m_buttonConfigure; }
    wxPanel* GetPanel622() { return m_panel622; }
    wxStaticText* GetStaticText282() { return m_staticText282; }
    wxSpinCtrl* GetMeasureInterval() { return m_MeasureInterval; }
    wxStaticText* GetStaticText286() { return m_staticText286; }
    wxSpinCtrl* GetPublishInterval() { return m_PublishInterval; }
    wxCheckBox* GetEnabled() { return m_Enabled; }
    wxCheckBox* GetEnableTabView() { return m_EnableTabView; }
    wxPanel* GetPanel265() { return m_panel265; }
    SPS30SetupDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("SPS30  Setup"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(300,300), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~SPS30SetupDialogBase();
};


class Sps30PanelBase : public wxPanel
{
protected:
    wxBoxSizer* boxSizer759;
    wxGrid* m_grid;

protected:

public:
    wxGrid* GetGrid() { return m_grid; }
    Sps30PanelBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~Sps30PanelBase();
};

#endif
